language: node_js

node_js:
  - 'node'
  - 'lts/*'

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

notifications:
  email:
    on_failure: change
